apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-ingress
  namespace: tum-study-planner-monitoring
  labels:
    app: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # Enable basic auth for security
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: monitoring-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - Monitoring"
spec:
  rules:
    - host: monitoring.tum-study-planner.local
      http:
        paths:
          - path: /prometheus
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
          - path: /alertmanager
            pathType: Prefix
            backend:
              service:
                name: alertmanager
                port:
                  number: 9093
---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-auth
  namespace: tum-study-planner-monitoring
  labels:
    app: monitoring
type: Opaque
data:
  # htpasswd -nb admin secure-password | base64
  # Default: admin:secure-monitoring-password
  auth: YWRtaW46JGFwcjEkdUQuTy5EUFMKTXZ4NDBOb1V6Y3NCVm5jbUtYSDBR
