apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: tum-study-planner-monitoring
  labels:
    app: prometheus
    monitoring: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus
  namespace: tum-study-planner-monitoring
  labels:
    app: prometheus
    monitoring: "true"
rules:
  - apiGroups: [""]
    resources:
      - services
      - endpoints
      - pods
      - configmaps
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus
  namespace: tum-study-planner-monitoring
  labels:
    app: prometheus
    monitoring: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: tum-study-planner-monitoring
---
# Also create a role for application namespace monitoring
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-app-monitor
  namespace: tum-study-planner
  labels:
    app: prometheus
    monitoring: "true"
rules:
  - apiGroups: [""]
    resources:
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-app-monitor
  namespace: tum-study-planner
  labels:
    app: prometheus
    monitoring: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-app-monitor
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: tum-study-planner-monitoring
