apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "team-stratton-oakmont.labels" . | nindent 4 }}
    app: client
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
  selector:
    app: frontend