{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "team-stratton-oakmont.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "team-stratton-oakmont.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - team-stratton-oakmont.student.k8s.aet.cit.tum.de
      secretName: team-stratton-oakmont-tls
  rules:
    - host: team-stratton-oakmont.student.k8s.aet.cit.tum.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  number: {{ .Values.frontend.service.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: server-service
                port:
                  number: {{ .Values.backend.service.port }}
{{- end }}