apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "team-stratton-oakmont.labels" . | nindent 4 }}
    app: server
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
  selector:
    app: backend