services:
  # Program Catalog Service
  program-catalog-service:
    build:
      context: ./server
      dockerfile: program-catalog-service/Dockerfile
    container_name: program-catalog-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - stratton-oakmont-network
    restart: unless-stopped

  # Study Plan Service
  study-plan-service:
    build:
      context: ./server
      dockerfile: study-plan-service/Dockerfile
    container_name: study-plan-service
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - stratton-oakmont-network
    restart: unless-stopped

  # AI Advisor Service
  ai-advisor-service:
    build:
      context: ./server
      dockerfile: ai-advisor-service/Dockerfile
    container_name: ai-advisor-service
    ports:
      - "8082:8082"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - stratton-oakmont-network
    restart: unless-stopped

  # User Auth Service
  user-auth-service:
    build:
      context: ./server
      dockerfile: user-auth-service/Dockerfile
    container_name: user-auth-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
    networks:
      - stratton-oakmont-network
    restart: unless-stopped

  # LLM Inference Service (Python)
  llm-inference-service:
    build:
      context: ./server/llm-inference-service
    container_name: llm-inference-service
    ports:
      - "8084:8084"
    env_file:
      - .env
    environment:
      - ENV=production
    networks:
      - stratton-oakmont-network
    restart: unless-stopped

  # Client (React Frontend)
  client:
    build:
      context: ./client
      args:
        - NODE_ENV=production
        - VITE_MODE=production
        - VITE_API_BASE_URL=${PUBLIC_IP:-localhost}:8083
    container_name: stratton-oakmont-client
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - program-catalog-service
      - study-plan-service
      - user-auth-service
      - ai-advisor-service
    networks:
      - stratton-oakmont-network
    restart: unless-stopped

networks:
  stratton-oakmont-network:
    driver: bridge
