# prettier-ignore
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: client
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: {{ .Values.resources.client.requests.cpu }}
              memory: {{ .Values.resources.client.requests.memory }}
            limits:
              cpu: {{ .Values.resources.client.limits.cpu }}
              memory: {{ .Values.resources.client.limits.memory }}
