# prettier-ignore
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unified-swagger-ui
  namespace: {{ .Values.namespace }}
  labels:
    app: unified-swagger-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unified-swagger-ui
  template:
    metadata:
      labels:
        app: unified-swagger-ui
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: swagger-ui-volume
              mountPath: /usr/share/nginx/html
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: swagger-ui-volume
          configMap:
            name: unified-swagger-ui
