# prettier-ignore
apiVersion: v1
kind: Service
metadata:
  name: study-plan-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: study-plan-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
    - name: management
      port: 9081
      targetPort: 9081
  type: ClusterIP
