# prettier-ignore
apiVersion: v1
kind: Service
metadata:
  name: user-auth-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: user-auth-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
    - name: management
      port: 9083
      targetPort: 9083
  type: ClusterIP
