# prettier-ignore
apiVersion: v1
kind: Service
metadata:
  name: ai-advisor-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: ai-advisor-service
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP
