# prettier-ignore
apiVersion: v1
kind: Service
metadata:
  name: llm-inference-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: llm-inference-service
  ports:
    - port: {{ .Values.services.llmInferenceService.port }}
      targetPort: {{ .Values.services.llmInferenceService.targetPort }}
  type: ClusterIP
