# prettier-ignore
apiVersion: v1
kind: Service
metadata:
  name: user-auth-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: user-auth-service
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP
