# prettier-ignore
apiVersion: v1
kind: Service
metadata:
  name: ai-advisor-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: ai-advisor-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
    - name: management
      port: 9082
      targetPort: 9082
  type: ClusterIP
