apiVersion: apps/v1
kind: Deployment
metadata:
  name: program-catalog-service
  namespace: tum-study-planner
  labels:
    app: program-catalog-service
    component: backend
    monitoring: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: program-catalog-service
  template:
    metadata:
      labels:
        app: program-catalog-service
        component: backend
        monitoring: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: program-catalog-service
          image: program-catalog-service:latest
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9080
              name: metrics
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,info,metrics,prometheus"
            - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
              value: "true"
            - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
              value: "true"
          envFrom:
            - configMapRef:
                name: tum-study-planner-config
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9080
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9080
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: program-catalog-service
  namespace: tum-study-planner
  labels:
    app: program-catalog-service
    component: backend
    monitoring: "true"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9080"
    prometheus.io/path: "/actuator/prometheus"
spec:
  selector:
    app: program-catalog-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 9080
      targetPort: 9080
  type: ClusterIP
