# Global configuration
namespace: tum-study-planner

# Ingress configuration
ingress:
  host: tum-study-planner.student.k8s.aet.cit.tum.de
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /

# TODO: Change to team ghcr once available
# Client (Frontend) configuration
client:
  image:
    repository: ghcr.io/florivn/client
    tag: latest

# Study Plan Service configuration
studyPlanService:
  image:
    repository: ghcr.io/florivn/study-plan-service
    tag: latest

# Program Catalog Service configuration
programCatalogService:
  image:
    repository: ghcr.io/florivn/program-catalog-service
    tag: latest

# AI Advisor Service configuration
aiAdvisorService:
  image:
    repository: ghcr.io/florivn/ai-advisor-service
    tag: latest

# User Auth Service configuration
userAuthService:
  image:
    repository: ghcr.io/florivn/user-auth-service
    tag: latest

# Database configurations (using existing k8s manifests)
postgresql:
  enabled: false # We're using separate manifests in k8s/base/

# Environment-specific overrides
environment: production
