# Global configuration
namespace: tum-study-planner

# Ingress configuration
ingress:
  host: tum-study-planner.student.k8s.aet.cit.tum.de
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /

# Client (Frontend) configuration
client:
  image:
    repository: ghcr.io/AET-DevOps25/team-stratton-oakmont/client
    tag: latest

# Study Plan Service configuration
studyPlanService:
  image:
    repository: ghcr.io/AET-DevOps25/team-stratton-oakmont/study-plan-service
    tag: latest

# Program Catalog Service configuration
programCatalogService:
  image:
    repository: ghcr.io/AET-DevOps25/team-stratton-oakmont/program-catalog-service
    tag: latest

# AI Advisor Service configuration
aiAdvisorService:
  image:
    repository: ghcr.io/AET-DevOps25/team-stratton-oakmont/ai-advisor-service
    tag: latest

# LLM Inference Service configuration
llmInferenceService:
  image:
    repository: ghcr.io/AET-DevOps25/team-stratton-oakmont/llm-inference-service
    tag: latest
  env:
    WEAVIATE_URL: "http://weaviate-vector-service.tum-study-planner:8080"
    WEAVIATE_GRPC_URL: "http://weaviate-vector-service.tum-study-planner:50051"
    STUDY_DATA_DB_HOST: "postgres-study-data-service"
    STUDY_DATA_DB_PORT: "5432"
    STUDY_DATA_DB_NAME: "study_data_db"
    STUDY_PLAN_DB_HOST: "postgres-study-plan-service"
    STUDY_PLAN_DB_PORT: "5432"
    STUDY_PLAN_DB_NAME: "study_plan_db"
    # GOOGLE_API_KEY: "your_google_api_key_here"

# User Auth Service configuration
userAuthService:
  image:
    repository: ghcr.io/AET-DevOps25/team-stratton-oakmont/user-auth-service
    tag: latest

# Swagger UI configuration
swaggerUi:
  image:
    repository: ghcr.io/AET-DevOps25/team-stratton-oakmont/swagger-ui
    tag: latest

# Database configurations (using existing k8s manifests)
postgresql:
  enabled: false # We're using separate manifests in k8s/base/

# Environment-specific overrides
environment: production
