---
- name: Deploy TUM Study Planner Application
  hosts: webservers
  become: yes
  vars:
    a    - name: Stop existing application services
      command: docker-compose -f docker-compose.prod.yml down
      args:
        chdir: "{{ app_dir }}"
      become_user: ec2-user
      ignore_errors: yes

    - name: Stop existing monitoring services
      command: docker-compose -f docker-compose.monitoring.yml down
      args:
        chdir: "{{ app_dir }}"
      become_user: ec2-user
      ignore_errors: yes

    - name: Create shared Docker network
      command: docker network create stratton-oakmont-network
      become_user: ec2-user
      ignore_errors: yes

    - name: Start monitoring stack first
      command: docker-compose -f docker-compose.monitoring.yml up -d
      args:
        chdir: "{{ app_dir }}"
      become_user: ec2-user
      async: 300
      poll: 10

    - name: Wait for monitoring to be ready
      wait_for:
        port: "{{ item }}"
        delay: 5
        timeout: 120
      loop:
        - 9090 # Prometheus
        - 3001 # Grafana
        - 3100 # Loki
        - 9084 # Promtail

    - name: Start application services with PUBLIC_IP environment variable
      command: docker-compose -f docker-compose.prod.yml up -d --build --force-recreate
      args:
        chdir: "{{ app_dir }}"
      become_user: ec2-user
      environment:
        PUBLIC_IP: "http://{{ public_ip }}"
      async: 500
      poll: 30
      register: compose_resultstudy-planner
    repo_url: https://github.com/AET-DevOps25/team-stratton-oakmont.git

  tasks:
    - name: Install required packages and setup Docker
      block:
        - name: Clean package cache
          command: yum clean all
          ignore_errors: yes

        - name: Install packages
          yum:
            name:
              - git
              - docker
            state: present
            update_cache: yes

    - name: Download and install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.24.1/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: "0755"
        owner: root
        group: root

    - name: Create docker-compose symlink
      file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Reset SSH connection to allow user group changes
      meta: reset_connection

    - name: Test Docker access for ec2-user
      command: docker --version
      become_user: ec2-user
      register: docker_test
      failed_when: docker_test.rc != 0

    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: "0755"

    - name: Clone application repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: "main"
        force: yes
      become_user: ec2-user

    - name: Get public IP address
      uri:
        url: http://checkip.amazonaws.com/
        return_content: yes
      register: public_ip_result

    - name: Set public IP fact
      set_fact:
        public_ip: "{{ public_ip_result.content | trim }}"

    - name: Debug public IP
      debug:
        msg: "Detected public IP: {{ public_ip }}"

    - name: Copy local environment file
      copy:
        src: "{{ playbook_dir }}/../.env" # This looks for .env in project root
        dest: "{{ app_dir }}/.env"
        owner: ec2-user
        group: ec2-user
        mode: "0600"

    - name: Stop any existing containers
      command: docker-compose -f docker-compose.prod.yml down --remove-orphans
      args:
        chdir: "{{ app_dir }}"
      become_user: ec2-user
      ignore_errors: yes

    - name: Start application services with PUBLIC_IP environment variable
      command: docker-compose -f docker-compose.prod.yml up -d --build --force-recreate
      args:
        chdir: "{{ app_dir }}"
      become_user: ec2-user
      environment:
        PUBLIC_IP: "http://{{ public_ip }}"
      async: 500
      poll: 30
      register: compose_result

    - name: Show Docker Compose output
      debug:
        var: compose_result

    - name: Wait for application services to be ready
      wait_for:
        port: "{{ item }}"
        delay: 10
        timeout: 300
      loop:
        - 80 # Nginx
        - 8080 # Program Catalog Service
        - 8081 # Study Plan Service
        - 8082 # AI Advisor Service
        - 8083 # User Auth Service
        - 8000 # LLM Service
