# Ansible inventory file for AWS EC2 instances

all:
  children:
    webservers:
      hosts:
        ec2-instance:
          ansible_host: "{{ instance_ip }}"
          ansible_user: ec2-user
          ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file }}"
          ansible_python_interpreter: /usr/bin/python3.9
      vars:
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
