# PVC for Auth DB
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-auth-pvc
  namespace: tum-study-planner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
# Auth PostgreSQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-auth
  namespace: tum-study-planner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-auth
  template:
    metadata:
      labels:
        app: postgres-auth
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: "auth_db"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: tum-study-planner-secrets
                  key: AUTH_POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tum-study-planner-secrets
                  key: AUTH_POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-auth-pvc
---
# Auth PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-auth-service
  namespace: tum-study-planner
spec:
  selector:
    app: postgres-auth
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
