apiVersion: v1
kind: Secret
metadata:
  name: tum-study-planner-secrets
  namespace: tum-study-planner
  labels:
    app: tum-study-planner
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # 'postgres'
  POSTGRES_PASSWORD: eW91cl9zZWN1cmVfcGFzc3dvcmRfaGVyZQ== # 'your_secure_password_here'
  JWT_SECRET: eW91cl9qd3Rfc2VjcmV0X2hlcmU= # 'your_jwt_secret_here'
